### ISSUE TITLE
Installed but 1 Error

### ISSUE THREAD

**Issue by Chioti** [rooi/homebridge-foscam#1]
I've installed everything per the directions.  Upon starting homebridge I get:
[TypeError: Cannot read property 'motionDetectAlarm' of undefined]

The camera does show up in my Elgato Eve app, but it simply shows up as a "motion" device.  Should it also show video?

**Comment by toshibochan** [comment]
How to use Siri to turn ON or OFF motion sensor?

**Comment by rooi** [comment]
@SteliosMakrinos I only have implemented the motion detection functionality in homekit. I would like to add some other functionality, like sending audio messages, but this is not that easy.
The error you receive probably indicates that this fiscal-client does not return the expected result. Could you check with just the foscam client and run the example? https://github.com/lightswitch05/foscam-client

@toshibochan turning on or off the motion sensor is not implemented (yet). I'm only using the motion detection as trigger for other accessories now.

**Comment by toshibochan** [comment]
I hope one day you can add function to turn ON an OFF just saying "hey Siri turn ON motion sensor".

**Comment by rooi** [comment]
@toshibochan I just had a look and it should be possible using the getMotionDetectConfig and setMotionDetectConfig cgi command, I think. However, my device (foscam c2) return an empty result when specifying this command, so I cannot implement it myself.

Perhaps you have another device and could try to implement it yourself. You can use the following command (replace the IP, port, usr, and password) to test if the command is working on your device.

http://IP_ADDRESS:PORT/cgi-bin/CGIProxy.fcgi?usr=admin&pwd=PASSWORD&cmd=getMotionDetectConfig

If this works, you could try the foscam-client mentioned above to try if it works using nodejs. After this, it should be easy to implement it in homebridge.

**Comment by toshibochan** [comment]
The link you is blank!

**Comment by toshibochan** [comment]
The link you sent is blank

**Comment by toshibochan** [comment]
how i use the command?

**Comment by rooi** [comment]
The same happens with my C2 and it should return a result. You can check other commands at: https://github.com/lightswitch05/foscam-client/blob/master/HD%20cameras%20SDK%20CGI%20(1)/Foscam%20IPCamera%20CGI%20User%20Guide-3518%20Ver.1.0.10.pdf

The following command is used to get the alarm state, for example:

http://IP_ADDRESS:PORT/cgi-bin/CGIProxy.fcgi?usr=admin&pwd=PASSWORD&cmd=getDevState

**Comment by toshibochan** [comment]
i have to type this on terminal?
http://IP_ADDRESS:PORT/cgi-bin/CGIProxy.fcgi?usr=admin&pwd=PASSWORD&cmd=getDevState

**Comment by toshibochan** [comment]
result is working

<CGI_Result>
    <result>0</result>
    <isEnable>1</isEnable>
    <linkage>3</linkage>
    <snapInterval>2</snapInterval>
    <sensitivity>0</sensitivity>
    <triggerInterval>5</triggerInterval>
    <schedule0>281474976710655</schedule0>
    <schedule1>281474976710655</schedule1>
    <schedule2>281474976710655</schedule2>
    <schedule3>281474976710655</schedule3>
    <schedule4>281474976710655</schedule4>
    <schedule5>281474976710655</schedule5>
    <schedule6>281474976710655</schedule6>
    <area0>1023</area0>
    <area1>1023</area1>
    <area2>1023</area2>
    <area3>1023</area3>
    <area4>1023</area4>
    <area5>1023</area5>
    <area6>1023</area6>
    <area7>1023</area7>
    <area8>1023</area8>
    <area9>1023</area9>
</CGI_Result>

**Comment by toshibochan** [comment]
<CGI_Result>
    <result>-2</result>
</CGI_Result>

**Comment by toshibochan** [comment]
what is the command for enable and disable motion detection? and how i can add to my homebridge?

**Comment by toshibochan** [comment]
i able to change doing "change value 0 to disable and 1 to enable

http://IPADDRESS:PORT/cgi-bin/CGIProxy.fcgi?&cmd=setMotionDetectConfig&isEnable=1&usr=USER&pwd=PASSWORD

**Comment by rooi** [comment]
Ah I see, I've just committed a change to github. Perhaps you can check if it works so I can publish it to npm

**Comment by toshibochan** [comment]
I'm not home for 2 to 3 weeks! I will test when I back!

**Comment by luisiam** [comment]
I just installed and I am still getting the `[TypeError: Cannot read property 'motionDetectAlarm' of undefined]`

**Comment by luisiam** [comment]
I also get `npm WARN EPEERINVALID cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.` during installation

**Comment by rooi** [comment]
@luisiam I just committed a fix that may fix the error you received. However, if I'm correct you should only have gotten this error one time on initiation. Is this correct?

The second warning you received seems to be related to the promise module version in the fiscal-client.
I bumped the version and issued a pull request for this module. Until it is merged you can try my fork at:

https://github.com/rooi/foscam-client

The plugin relies on the cgi interface and particularly on the following command:

http://IPADDRESS:PORT/cgi-bin/CGIProxy.fcgi?&cmd=getDevState&usr=USER&pwd=PASSWORD

Please try this in a browser to see if you can get a response if the plugin does not work. Note that only motion detection is implemented at the moment.

**Comment by luisiam** [comment]
The `TypeError` is one time only. I guess because the promise is asynchronous and  `motionDetectAlarm` got called before anything is assigned to it during initialization.

Even I had the 2nd error during installation, my plugin works correctly.

I also want to comment on the motion detection switch. If we simply set the `isEnable` param, all other settings won't be saved. For now, I just included all my settings manually in the param.

```
var params = {
                isEnable: enable,
                linkage: 14,                    // Send mail, Snap picture, Record
                snapInterval: 2,                // 2s
                sensitivity: 1,                 // Medium
                triggerInterval: 5,             // 10s
                schedule0: 281474976710655,     // Monday all day
                schedule1: 281474976710655,     // Tuesday all day
                schedule2: 281474976710655,     // Wednesday all day
                schedule3: 281474976710655,     // Thursday all day
                schedule4: 281474976710655,     // Friday all day
                schedule5: 281474976710655,     // Saturday all day
                schedule6: 281474976710655,     // Sunday all day
                area0: 1023,                    // area0 all effective
                area1: 1023,                    // area1 all effective
                area2: 1023,                    // area2 all effective
                area3: 1023,                    // area3 all effective
                area4: 1023,                    // area4 all effective
                area5: 1023,                    // area5 all effective
                area6: 1023,                    // area6 all effective
                area7: 1023,                    // area7 all effective
                area8: 1023,                    // area8 all effective
                area9: 1023                     // area9 all effective
            };
```

It will be nice if the program can remember the the previous setting.

**Comment by rooi** [comment]
Thanks for testing. I've send an email the foscam for their latest CGI document and with the question on why the getMotionDetectConfig command returns empty. This commands contains all the necessary parameters you mention above.

When I hear from them I'll try to improve the plugin

**Comment by toshibochan** [comment]
User and password have to be in the end for work.

http://IPADDRESS:PORT/cgi-bin/CGIProxy.fcgi?&cmd=getMotionDetectConfig&isEnable=1&usr=USER&pwd=PASSWORD

**Comment by rooi** [comment]
@luisiam 

I've just pushed a possible fix for losing your setting when enable/disabling the motion detection. I works for my C2, but perhaps you can check if it works for your device?

It uses the getMotionDetectConfig1 cgi command

**Comment by luisiam** [comment]
@rooi 

Mine doesn't work with `getMotionDetectConfig1` and `setMotionDetectConfig1`
Mine only works with `getMotionDetectConfig` and `setMotionDetectConfig`

I guess the C2 is newer and uses a newer API. I am using FI9821W V2 and FI9826W

**Comment by rooi** [comment]
Ah, It should be possible to make them work with both.
Perhaps check if the response to getMotionDetectConfig is empty end then use the getMotionDetectConfig1 function instead.
I'm off on vacation in a few days, perhaps you can help fix this before this time?

**Comment by luisiam** [comment]
@rooi 

Just created a PR. Took me a while to figure out the syntax. I don't have a CS major and I don't know shit about JS lol

**Comment by rooi** [comment]
@luisiam Thanks, works very well.
I just started learning nodejs as well, so don't use my code as too much of a guideline ;)

**Comment by toshibochan** [comment]
hi @luisiam you able to turn ON and Off motion sensor using siri?

**Comment by luisiam** [comment]
@toshibochan I haven't played with Siri command. I always use scenes and triggers. Now I have moved to `SecuritySystem` implementation (#5) and I cannot test it out

**Comment by rooi** [comment]
please try: https://github.com/luisiam/homebridge-foscamcamera
This repo can be considered deprecated
